### PR TITLE
added checking exercise to make sure the training is federated

### PR DESCRIPTION
**Pull request by octaviansima**

### CODE REVIEW

**Review by chester-leung — COMMENTED** [review]
Looks great! Is there any way to capture the number of bytes in addition to the number of packets?

**Comment by octaviansima** [comment]
sure, I'll update the PR in a couple of min

**Comment by chester-leung** [comment]
In the "Number of Bytes Sent" table, in the Transmission column, is there any way to replace the IPs with the role of the party? So instead of `151.101.189.140 -> 192.168.42.5` it'd show `worker1 -> master`.

Can you also combine the Number of Packets table and the Number of Bytes table, and sort the combined table by number of bytes sent in descending order? The (src ip, dest ip) pairs with the most bytes transmitted would therefore come first.

Lastly, I don't think we need to show the intermediate steps of the `capture` table. Maybe remove the first two `capture.head()` calls?

**Comment by octaviansima** [comment]
For readability, the users would input the IPs of their federation in the cell right under 'Set Variables For Network Analysis.' The values are then renamed accordingly in the cell right after the .csv is read in. I implemented the other changes requested; let me know if there's anything else

**Comment by chester-leung** [comment]
Thanks for the changes. This looks great!

**Pull request merged**
